project_id = "lwruwpwdrkmtgcapnbzc"

[functions.ai-stock-prediction]
verify_jwt = false

[functions.ai-profitability-analysis]
verify_jwt = false

[functions.ai-daily-summary]
verify_jwt = false

[functions.woocommerce-products]
verify_jwt = false

[functions.woocommerce-checkout]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.sync-ventas]
verify_jwt = false

[functions.sync-temperatura]
verify_jwt = false
